name: Deploy to GitHub Pages

on: [push]

jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Build
          run: echo "Hello, world!" > artifact.txt
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: example-artifact
            path: artifact.txt

      test:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - uses: actions/checkout@v3
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: example-artifact
        - name: Use artifact
          run: cat artifact.txt
